//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appHarborApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblState
    {
        public tblState()
        {
            this.tblCities = new HashSet<tblCity>();
        }
    
        public int StateId { get; set; }
        public string StateName { get; set; }
        public int refCountryId { get; set; }
    
        public virtual ICollection<tblCity> tblCities { get; set; }
        public virtual tblCountry tblCountry { get; set; }
    }
}
